IMS:
  - changed-files:
      - any-glob-to-any-file:
          - alicloud/service/ims/**
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - go.mod
          - go.sum
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - website/**/*