---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang, tag: 1.18.9}

inputs:
  - name: terraform-provider-alicloud
  - name: aliyun-cli

run:
  path: terraform-provider-alicloud/ci/tasks/docs-example.sh
params:
  ALICLOUD_ACCESS_KEY:   ""
  ALICLOUD_SECRET_KEY:   ""
  ALICLOUD_ACCOUNT_ID:   ""
  DING_TALK_TOKEN:       ""
  OSS_BUCKET_NAME:           ""
  OSS_BUCKET_REGION:         ""
  GITHUB_TOKEN: ""