---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang, tag: 1.13.4}

inputs:
  - name: terraform-provider-alicloud

run:
  path: terraform-provider-alicloud/ci/tasks/resource-test.sh
params:
  ALICLOUD_ACCESS_KEY:   ""
  ALICLOUD_SECRET_KEY:   ""
  ALICLOUD_REGION:       ""
  RESOURCE_NAME:         ""
