// Code generated by terramore. DO NOT EDIT.
// File: alicloud/data_source_alicloud_realtime_compute_variables_test.go
package alicloud

import (
	"fmt"
	"testing"

	"github.com/aliyun/terraform-provider-alicloud/alicloud/connectivity"
	"github.com/hashicorp/terraform-plugin-sdk/helper/acctest"
	"github.com/hashicorp/terraform-plugin-sdk/helper/resource"
)

func TestAccAlicloudRealtimeComputeVariables_basic0(t *testing.T) {
	rand := acctest.RandIntRange(10000, 99999)
	name := fmt.Sprintf("tf-acc-var-%d", rand)
	resourceId := "data.alicloud_realtime_compute_variables.default"
	ra := resourceAttrInit(resourceId, AlicloudRealtimeComputeVariablesMap0)
	rc := resourceCheckInit(resourceId, &map[string]interface{}{}, func() interface{} {
		return &RealtimeComputeServiceV2{testAccProvider.Meta().(*connectivity.AliyunClient)}
	})
	rac := resourceAttrCheckInit(rc, ra)
	testAccCheck := rac.resourceAttrMapUpdateSet()
	testAccConfig := resourceTestAccConfigFunc(resourceId, name, AlicloudRealtimeComputeVariableBasicDependence0)
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccPreCheckWithRegions(t, true, []connectivity.Region{"cn-beijing"})
			testAccPreCheck(t)
		},
		IDRefreshName: resourceId,
		Providers:     testAccProviders,
		Steps: []resource.TestStep{
			{
				Config: fmt.Sprintf(`
resource "alicloud_realtime_compute_variable" "default" {
  workspace   = "${alicloud_realtime_compute_vvp_instance.create_VvpInstance.resource_id}"
  namespace   = "${alicloud_realtime_compute_vvp_instance.create_VvpInstance.vvp_instance_name}-default"
  name        = "%s"
  kind        = "Plain"
  value       = "test-value"
  description = "datasource test variable"
}
`, name) + testAccConfig(map[string]interface{}{
					"workspace":   "${alicloud_realtime_compute_vvp_instance.create_VvpInstance.resource_id}",
					"namespace":   "${alicloud_realtime_compute_vvp_instance.create_VvpInstance.vvp_instance_name}-default",
					"name_regex":  "${alicloud_realtime_compute_variable.default.name}",
					"output_file": fmt.Sprintf("variables-%d.txt", rand),
				}),
				Check: resource.ComposeTestCheckFunc(
					testAccCheck(map[string]string{
						"ids.#":       CHECKSET,
						"variables.#": CHECKSET,
						"output_file": CHECKSET,
					}),
				),
			},
		},
	})
}

var AlicloudRealtimeComputeVariablesMap0 = map[string]string{
	"ids.#":       CHECKSET,
	"variables.#": CHECKSET,
	"output_file": CHECKSET,
}
