// Code generated by terramore. DO NOT EDIT.
// File: alicloud/data_source_alicloud_realtime_compute_variables.go
package alicloud

import (
	"fmt"
	"regexp"
	"time"

	"github.com/PaesslerAG/jsonpath"
	"github.com/aliyun/terraform-provider-alicloud/alicloud/connectivity"
	"github.com/hashicorp/terraform-plugin-sdk/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
)

func dataSourceAlicloudRealtimeComputeVariables() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlicloudRealtimeComputeVariablesRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
			},
			"workspace": {
				Type:     schema.TypeString,
				Required: true,
			},
			"namespace": {
				Type:     schema.TypeString,
				Required: true,
			},
			"name_regex": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"output_file": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"variables": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"workspace": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"namespace": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"name": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"kind": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"value": {
							Type:      schema.TypeString,
							Computed:  true,
							Sensitive: true,
						},
						"description": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"region_id": {
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlicloudRealtimeComputeVariablesRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AliyunClient)
	workspace := d.Get("workspace").(string)
	namespace := d.Get("namespace").(string)
	action := fmt.Sprintf("/api/v2/namespaces/%s/variables", namespace)
	header := make(map[string]*string)
	query := make(map[string]*string)
	header["workspace"] = StringPointer(workspace)

	var allObjects []interface{}
	pageIndex := 1
	pageSize := 100
	wait := incrementalWait(3*time.Second, 5*time.Second)

	for {
		query["pageSize"] = StringPointer(fmt.Sprintf("%d", pageSize))
		query["pageIndex"] = StringPointer(fmt.Sprintf("%d", pageIndex))

		var response map[string]interface{}
		var err error
		err = resource.Retry(1*time.Minute, func() *resource.RetryError {
			response, err = client.RoaGet("ververica", "2022-07-18", action, query, header, nil)
			if err != nil {
				if NeedRetry(err) {
					wait()
					return resource.RetryableError(err)
				}
				return resource.NonRetryableError(err)
			}
			return nil
		})
		addDebug(action, response, make(map[string]interface{}))
		if err != nil {
			if IsExpectedErrors(err, []string{"990301"}) {
				d.SetId(fmt.Sprintf("%v:%v", workspace, namespace))
				return nil
			}
			return WrapErrorf(err, DefaultErrorMsg, "data.alicloud_realtime_compute_variables", action, AlibabaCloudSdkGoERROR)
		}

		dataRaw, e := jsonpath.Get("$.data", response)
		if e != nil {
			return WrapErrorf(e, FailedGetAttributeMsg, "data.alicloud_realtime_compute_variables", "$.data", response)
		}
		var data []interface{}
		if dataSlice, ok := dataRaw.([]interface{}); ok {
			data = dataSlice
		}
		if len(data) == 0 {
			break
		}
		allObjects = append(allObjects, data...)

		totalSize := 0
		if v, ok := response["totalSize"]; ok {
			if ts, ok2 := v.(float64); ok2 {
				totalSize = int(ts)
			}
		}
		if len(allObjects) >= totalSize || len(data) < pageSize {
			break
		}
		pageIndex++
	}

	var filteredObjects []map[string]interface{}
	var nameRegex *regexp.Regexp
	if v, ok := d.GetOk("name_regex"); ok && v.(string) != "" {
		r, e := regexp.Compile(v.(string))
		if e != nil {
			return WrapError(e)
		}
		nameRegex = r
	}

	ids := make([]string, 0)
	for _, obj := range allObjects {
		item := obj.(map[string]interface{})
		name := fmt.Sprint(item["name"])
		if nameRegex != nil && !nameRegex.MatchString(name) {
			continue
		}
		variableMap := map[string]interface{}{
			"id":          fmt.Sprintf("%v:%v:%v", workspace, namespace, name),
			"workspace":   workspace,
			"namespace":   namespace,
			"name":        name,
			"kind":        item["kind"],
			"value":       item["value"],
			"description": item["description"],
			"region_id":   client.RegionId,
		}
		filteredObjects = append(filteredObjects, variableMap)
		ids = append(ids, variableMap["id"].(string))
	}

	d.SetId(fmt.Sprintf("%v:%v", workspace, namespace))
	d.Set("variables", filteredObjects)
	d.Set("ids", ids)

	if output, ok := d.GetOk("output_file"); ok && output.(string) != "" {
		if err := writeToFile(output.(string), filteredObjects); err != nil {
			return WrapError(err)
		}
	}

	return nil
}
