package alicloud

const (
	HOST_GROUP_TYPE_MASTER  = string("MASTER")
	HOST_GROUP_TYPE_CORE    = string("CORE")
	HOST_GROUP_TYPE_TASK    = string("TASK")
	HOST_GROUP_TYPE_GATEWAY = string("GATEWAY")

	DEPOSIT_TYPE_FULLY_MANAGED = string("FULLY_MANAGED")
	DEPOSIT_TYPE_HALF_MANAGED  = string("HALF_MANAGED")
)
