package alicloud

import (
	"fmt"
	"testing"

	"github.com/aliyun/terraform-provider-alicloud/alicloud/connectivity"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/acctest"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

// Test ESA ClientCaCertificate. >>> Resource test cases, automatically generated.
// Case resource_ClientCaCertificate_set_test
func TestAccAliCloudESAClientCaCertificateresource_ClientCaCertificate_set_test(t *testing.T) {
	var v map[string]interface{}
	resourceId := "alicloud_esa_client_ca_certificate.default"
	ra := resourceAttrInit(resourceId, AliCloudESAClientCaCertificateresource_ClientCaCertificate_set_testMap)
	rc := resourceCheckInitWithDescribeMethod(resourceId, &v, func() interface{} {
		return &EsaServiceV2{testAccProvider.Meta().(*connectivity.AliyunClient)}
	}, "DescribeEsaClientCaCertificate")
	rac := resourceAttrCheckInit(rc, ra)
	testAccCheck := rac.resourceAttrMapUpdateSet()
	rand := acctest.RandIntRange(10000, 99999)
	name := fmt.Sprintf("tf-testacc%sESAClientCaCertificate%d", defaultRegionToTest, rand)

	testAccConfig := resourceTestAccConfigFunc(resourceId, name, AliCloudESAClientCaCertificateresource_ClientCaCertificate_set_testBasicDependence)
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccPreCheck(t)
			testAccPreCheckWithRegions(t, true, []connectivity.Region{"cn-hangzhou"})
		},
		IDRefreshName: resourceId,
		ProviderFactories: testAccProviderFactory,
		CheckDestroy:  rac.checkResourceDestroy(),
		Steps: []resource.TestStep{
			{
				Config: testAccConfig(map[string]interface{}{
					"client_ca_cert_name": "test",
					"site_id":             "${data.alicloud_esa_sites.default.sites.0.id}",
					"certificate":         testEsaClientCaCertificate,
				}),
				Check: resource.ComposeTestCheckFunc(
					testAccCheck(map[string]string{}),
				),
			},
			{
				Config: testAccConfig(map[string]interface{}{}),
				Check: resource.ComposeTestCheckFunc(
					testAccCheck(map[string]string{}),
				),
			},
			{
				ResourceName:            resourceId,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{},
			},
		},
	})
}

var AliCloudESAClientCaCertificateresource_ClientCaCertificate_set_testMap = map[string]string{
	"id": CHECKSET,
}

func AliCloudESAClientCaCertificateresource_ClientCaCertificate_set_testBasicDependence(name string) string {
	return fmt.Sprintf(`
variable "name" {
    default = "%s"
}

data "alicloud_esa_sites" "default" {
  plan_subscribe_type = "enterpriseplan"
  site_name = "gositecdn.cn"
}

`, name)
}

// Test ESA ClientCaCertificate. <<< Resource test cases, automatically generated.
// generated by https://www.ssleye.com/ssltool/self_sign.html
const testEsaClientCaCertificate = `-----BEGIN CERTIFICATE-----\nMIIDLDCCAhSgAwIBAgIUbW7alHwt3HICHGVsLkqpW9Cd4oIwDQYJKoZIhvcNAQEL\nBQAwLjEQMA4GA1UEAwwHdGVzdC1jYTENMAsGA1UECgwEdGVzdDELMAkGA1UEBhMC\nQ04wHhcNMjYwNjAxMDMyMzEzWhcNMzYwNTI5MDMyMzEzWjAuMRAwDgYDVQQDDAd0\nZXN0LWNhMQ0wCwYDVQQKDAR0ZXN0MQswCQYDVQQGEwJDTjCCASIwDQYJKoZIhvcN\nAQEBBQADggEPADCCAQoCggEBAJvUEYwZodySRvwKaHVFgJsGe85tXYDzcHMlBS/7\n904+hVg/zPn3W83vlGHg0S9TUjDDYz+mx9XtGqbVTLNsnAFw6jnPvg6LoK3BE6fN\nT/muS4tkVN7zfKekC6RIPqpDoZEAVfXNzIdg31WdRhfDsUZ7ZgseTsh/o+0ophq/\nz8MwlLd0PYJJNQx+lvmBsBaqXKZ15+TXN4WwZ4Y0euXrX5uCd/eU+KrtsultZb/5\nF1yGR7ON2QCeYe0F1Csi+mdfuniipBtt4evtGRFRkTewzLPSoo8R/IokO50vtfl7\nNTTlwVw+N777PJZF5j0XdjGWtlxL98XpxkugpXSzsWUAewMCAwEAAaNCMEAwDwYD\nVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0OBBYEFIPFTEjW2zDy\nKmmsULjCisAJyu9QMA0GCSqGSIb3DQEBCwUAA4IBAQCSbwv8pOa1Tmv3eUCju4lW\n09JIYAE+H6n3tYRCwao0UdJ69c8yyNVVzbYf/3IbYBPs73OwW8sk3kKlZAHaPcUF\nFsCixLskgWKrJyCcK+sCt0c8JC+GeBHmJcncaq0E7XzxNB5R0KY2w6S7KCjeK1G9\niNsxvAVqNpISuHByd1LNKOT5S1niUx9Yd9eQTCcXEzZnE8Y2tf+gkUPjG9+5kxKL\nXHT3Choi7HjUYmwduKpV7wOAJdlBuyHegBii2xzRhdSriqffbqfczy9D5XSC6Q+w\nyF2ugGWW1IXF10DkMH3ixzbdGTohIUHpRZea3ELKhshMEo6ZqIhCLG3dv1kyeRG+\n-----END CERTIFICATE-----`
