#!/usr/bin/env bash

set -euo pipefail

# Check goimports
echo "==> Checking the code complies with goimports requirements..."

# We only require goimports to have been run on files that were changed
# relative to the main branch, so that we can gradually create more consistency
# rather than bulk-changing everything at once.

base_branch="origin/master"

# HACK: If we seem to be running inside a GitHub Actions pull request check
# then we'll use the PR's target branch from this variable instead.
if [[ -n "${GITHUB_BASE_REF:-}" ]]; then
  base_branch="origin/$GITHUB_BASE_REF"
fi

# Get changed Go files (compatible with Bash 3)
# NOTE: Intentionally excludes .pb.go files because those are
# generated by a tool (protoc-gen-go) which itself doesn't produce
# style-compliant imports.
target_files=$(git diff --name-only ${base_branch} --diff-filter=MA 2>/dev/null | grep "\.go$" | grep -v ".pb.go" | grep -v ".go-version" || true)

if [[ -z "$target_files" ]]; then
  echo "No files have changed relative to branch ${base_branch}, so there's nothing to check!"
  exit 0
fi

# Check each file for import issues (compatible with Bash 3)
incorrect_files=""

while IFS= read -r filename; do
  if [[ -z "$filename" ]]; then
    continue
  fi

  if [[ ! -f "$filename" ]]; then
    continue
  fi

  # Use installed goimports command instead of 'go run' to avoid updating go.mod
  if command -v goimports &> /dev/null; then
    output=$(goimports -l "${filename}" 2>&1)
  else
    output=$(go run golang.org/x/tools/cmd/goimports -l "${filename}" 2>&1)
  fi

  if [[ $? -ne 0 ]]; then
    echo >&2 "goimports failed for $filename"
    exit 1
  fi

  if [[ -n "$output" ]]; then
    incorrect_files="$incorrect_files$filename"$'\n'
  fi
done <<< "$target_files"

if [[ -n "$incorrect_files" ]]; then
  echo >&2 'The following files have import statements that disagree with "goimports"':
  echo "$incorrect_files" | sed 's/^/ - /' >&2
  echo >&2 'Use `goimports -w -l` on each of these files to update these files.'
  exit 1
fi

echo 'All of the changed files look good!'
exit 0
