groups:
  - name: all
    jobs:
#      - build-terraform-provider-package
      - point-to-point-ci-test

shared:

  - &run
    task: terraformci
    file: terraform-provider-alicloud/ci/tasks/ci-test.yml
    params:
      ALICLOUD_ACCESS_KEY: {{alicloud_access_key}}
      ALICLOUD_SECRET_KEY: {{alicloud_secret_key}}
      ALICLOUD_REGION: {{alicloud_region}}
      DING_TALK_TOKEN: {{ding_talk_token}}
      ALICLOUD_ACCOUNT_ID: {{alicloud_accound_id}}
      ALICLOUD_RESOURCE_GROUP_ID: {{alicloud_resource_group_id}}
      ALICLOUD_WAF_INSTANCE_ID: {{alicloud_waf_instance_id}}
      CONCOURSE_TARGET: {{alicloud_concourse_target}}
      CONCOURSE_TARGET_URL: {{alicloud_concourse_target_url}}
      CONCOURSE_TARGET_USER: {{alicloud_concourse_target_user}}
      CONCOURSE_TARGET_PASSWORD: {{alicloud_concourse_target_password}}
      TRIGGER_TARGET_PIPELINE: {{alicloud_trigger_target_pipeline}}
      ENTERPRISE_ACCOUNT_ENABLED: {{enterprise_account_enabled}}
      ALICLOUD_EXPRESS_CONNECT_UID: {{alicloud_express_connect_uid}}

jobs:
#  - name: build-terraform-provider-package
#    serial: true
#    plan:
#    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
#      - aggregate:
#          - *get-aliyun-cli
#      - <<: *build

- name: point-to-point-ci-test
  plan:
  - in_parallel:
    - get: terraform-provider-alicloud
      resource: terraform-provider-alicloud
      trigger: true
    - get: aliyun-cli
      resource: aliyun-cli
  - <<: *run

resources:
- name: terraform-provider-alicloud
  type: git
  source:
    uri: https://github.com/aliyun/terraform-provider-alicloud.git
    branch: master
    paths:
      - alicloud/*
      - vendor/*
      - go.mod
      - main.go

- name: aliyun-cli
  type: s3
  source:
    access_key_id: {{aliyun_cli_access_key}}
    secret_access_key: {{aliyun_cli_secret_key}}
    bucket: {{aliyun_cli_bucket}}
    regexp: .*-cli-linux-3\.0\.(\d+)-amd64\.tgz
    region_name: {{aliyun_cli_region}}
    endpoint: oss-((aliyun_cli_region)).aliyuncs.com
