---
groups:
  - name: All
    jobs:
      - verify-existed-resource
      - verify-new-resource

shared:
  - &validate
    task: validate
    file: terraform-provider-alicloud/ci/tasks/module-test.yml
    params: &validate-params
      ALICLOUD_ACCESS_KEY: {{alicloud_access_key}}
      ALICLOUD_SECRET_KEY: {{alicloud_secret_key}}
      ALICLOUD_REGION: {{alicloud_region}}
      terraform_version: {{terraform_version}}
  - &clone-provider
    get: terraform-provider-alicloud
    resource: terraform-provider-alicloud
    trigger: true




jobs:
  - name: verify-existed-resource
    serial: true
    plan:
      - <<: *clone-provider
      - get: aliyun-cli
        trigger: false
        resource: aliyun-cli
      - <<: *validate
        params:
          <<: *validate-params
          terraform_version: "1.1.1"
          Stage: "PrevStage"
      - <<: *validate
        params:
          <<: *validate-params
          terraform_version: "1.1.1"
          Stage: "NextStage"
  - name: verify-new-resource
    serial: true
    plan:
      - <<: *clone-provider
      - get: aliyun-cli
        trigger: false
        resource: aliyun-cli
      - <<: *validate
        params:
          <<: *validate-params
          terraform_version: "1.1.1"
          Stage: "NewVersion"


resources:
  - name: terraform-provider-alicloud
    type: git
    source:
      uri: https://github.com/Wanghx0991/terraform-provider-alicloud.git
      branch: point_module_test
  - name: aliyun-cli
    type: s3
    source:
      access_key_id: {{aliyun_cli_access_key}}
      secret_access_key: {{aliyun_cli_secret_key}}
      bucket: {{aliyun_cli_bucket}}
      regexp: .*-cli-linux-3\.0\.(\d+)-amd64\.tgz
      region_name: {{aliyun_cli_region}}
      endpoint: oss-((aliyun_cli_region)).aliyuncs.com
