groups:
  - name: All
    jobs:
      - Zones

shared:
  - &clone-provider
    get: terraform-provider-alicloud
    resource: terraform-provider-alicloud
    trigger: false

  - &get-terraform-qa
    get: terraform-qa
    resource: terraform-qa
    trigger: true

  - &get-aliyun-cli
    get: aliyun-cli
    resource: aliyun-cli

  - &run
    task: terraform ci
    file: terraform-provider-alicloud/ci/tasks/qa-test.yml
    params: &run-params
      TF_TASK_ACCESS_KEY: {{terraform_task_access_key}}
      TF_TASK_SECRET_KEY: {{terraform_task_secret_key}}

jobs:
  - name: Zones
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - aggregate:
          - *get-terraform-qa
          - *get-aliyun-cli
      - <<: *run
        params:
          <<: *run-params
          TEST_CASE_CODE: "Zones"

resources:
  - name: terraform-provider-alicloud
    type: git
    source:
      uri: https://github.com/aliyun/terraform-provider-alicloud.git
      branch: xiaozhu

  - name: aliyun-cli
    type: s3
    source:
      access_key_id: {{aliyun_cli_access_key}}
      secret_access_key: {{aliyun_cli_secret_key}}
      bucket: {{aliyun_cli_bucket}}
      regexp: .*-cli-linux-3\.0\.(\d+)-amd64\.tgz
      region_name: {{aliyun_cli_region}}
      endpoint: oss-((aliyun_cli_region)).aliyuncs.com

  - name: terraform-qa
    type: git
    source:
      uri: https://github.com/xiaozhu36/terraform-qa.git
      branch: main