groups:
  - name: all
    jobs:
      - cn-hangzhou-1
      - cn-hangzhou-2
      - cn-hangzhou-3
      - cn-hangzhou-4
      - cn-hangzhou-5
      - cn-beijing-1
      - cn-beijing-2
      - cn-beijing-3
      - cn-beijing-4
      - cn-beijing-5
      - cn-shanghai-1
      - cn-shanghai-2
      - cn-shanghai-3
      - cn-shanghai-4
      - cn-shanghai-5
      - eu-central-1-1
      - eu-central-1-2
      - eu-central-1-3
      - eu-central-1-4
      - eu-central-1-5
      - ap-southeast-1-1
      - ap-southeast-1-2
      - ap-southeast-1-3
      - ap-southeast-1-4
      - ap-southeast-1-5

shared:
  - &run
    task: terraformci
    file: terraform-provider-alicloud/ci/tasks/run.yml
    params: &run-params
      ALICLOUD_ACCESS_KEY: {{alicloud_access_key}}
      ALICLOUD_SECRET_KEY: {{alicloud_secret_key}}
      ALICLOUD_REGION: "cn-hangzhou"
      ALICLOUD_ACCOUNT_SITE: {{alicloud_account_site}}
      TEST_CASE_CODE: "-"
      SWEEPER: true
      # NOTE: If the account is not for the integration, there should set SWEEP_ALL to false
      SWEEP_ALL: true
      ALICLOUD_ACCOUNT_ID: {{alicloud_accound_id}}
      ALICLOUD_ACCESS_KEY_MASTER: {{alicloud_access_key_master}}
      ALICLOUD_SECRET_KEY_MASTER: {{alicloud_secret_key_master}}
      ALICLOUD_ACCESS_KEY_SLAVE:  {{alicloud_access_key_slave}}
      ALICLOUD_SECRET_KEY_SLAVE:  {{alicloud_secret_key_slave}}

jobs:
  - name: cn-hangzhou-1
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper1
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params

  - name: cn-hangzhou-2
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper2
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params

  - name: cn-hangzhou-3
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper3
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params

  - name: cn-hangzhou-4
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper4
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params

  - name: cn-hangzhou-5
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper5
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params

  - name: cn-beijing-1
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper1
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "cn-beijing"

  - name: cn-beijing-2
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper2
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "cn-beijing"

  - name: cn-beijing-3
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper3
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "cn-beijing"

  - name: cn-beijing-4
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper4
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "cn-beijing"

  - name: cn-beijing-5
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper5
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "cn-beijing"

  - name: cn-shanghai-1
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper1
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "cn-shanghai"

  - name: cn-shanghai-2
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper2
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "cn-shanghai"

  - name: cn-shanghai-3
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper3
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "cn-shanghai"

  - name: cn-shanghai-4
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper4
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "cn-shanghai"

  - name: cn-shanghai-5
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper5
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "cn-shanghai"

  - name: eu-central-1-1
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper1
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "eu-central-1"

  - name: eu-central-1-2
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper2
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "eu-central-1"

  - name: eu-central-1-3
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper3
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "eu-central-1"

  - name: eu-central-1-4
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper4
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "eu-central-1"

  - name: eu-central-1-5
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper5
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "eu-central-1"

  - name: ap-southeast-1-1
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper1
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "ap-southeast-1"

  - name: ap-southeast-1-2
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper2
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "ap-southeast-1"

  - name: ap-southeast-1-3
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper3
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "ap-southeast-1"

  - name: ap-southeast-1-4
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper4
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "ap-southeast-1"

  - name: ap-southeast-1-5
    plan:
    - in_parallel:
      - get: terraform-provider-alicloud
        resource: terraform-provider-alicloud
      - get: trigger
        trigger: true
        resource: sweeper5
      - get: aliyun-cli
        resource: aliyun-cli
    - <<: *run
      params:
        <<: *run-params
        ALICLOUD_REGION: "ap-southeast-1"

resources:
  - name: terraform-provider-alicloud
    type: git
    source:
      uri: https://github.com/aliyun/terraform-provider-alicloud.git
      branch: master

  - name: aliyun-cli
    type: s3
    source:
      access_key_id: {{aliyun_cli_access_key}}
      secret_access_key: {{aliyun_cli_secret_key}}
      bucket: {{aliyun_cli_bucket}}
      regexp: .*-cli-linux-3\.0\.(\d+)-amd64\.tgz
      region_name: {{aliyun_cli_region}}
      endpoint: oss-((aliyun_cli_region)).aliyuncs.com

  #apply to sweeper
  - name: sweeper1
    type: time
    source:
      start: 04:00 PM
      stop: 10:00 PM
      days: [Sunday, Saturday]
      location: {{time_location}}

  - name: sweeper2
    type: time
    source:
      start: 05:00 PM
      stop: 10:00 PM
      days: [Sunday, Saturday]
      location: {{time_location}}

  - name: sweeper3
    type: time
    source:
      start: 06:00 PM
      stop: 10:00 PM
      days: [Sunday, Saturday]
      location: {{time_location}}

  - name: sweeper4
    type: time
    source:
      start: 07:00 PM
      stop: 10:00 PM
      days: [Sunday, Saturday]
      location: {{time_location}}

  - name: sweeper5
    type: time
    source:
      start: 08:00 PM
      stop: 10:00 PM
      days: [Sunday, Saturday]
      location: {{time_location}}