groups:
  - name: All
    jobs:
      - build-terraform-provider-package

shared:
  - &clone-provider
    get: terraform-provider-alicloud
    resource: terraform-provider-alicloud
    trigger: true

  - &get-aliyun-cli
    get: aliyun-cli
    resource: aliyun-cli
  - &build
    task: build
    file: terraform-provider-alicloud/ci/tasks/build-package.yml
    params:
      terraform_provider_access_key: {{alicloud_access_key}}
      terraform_provider_secret_key: {{alicloud_secret_key}}
      terraform_provider_bucket_name: {{terraform_provider_bucket_name}}
      terraform_provider_bucket_region: {{terraform_provider_bucket_region}}

jobs:
  - name: build-terraform-provider-package
    serial: true
    plan:
      - <<: *clone-provider
      - aggregate:
          - *get-aliyun-cli
      - <<: *build

resources:
- name: terraform-provider-alicloud
  type: git
  source:
    uri: https://github.com/aliyun/terraform-provider-alicloud.git
    branch: xiaozhu

- name: aliyun-cli
  type: s3
  source:
    access_key_id: {{aliyun_cli_access_key}}
    secret_access_key: {{aliyun_cli_secret_key}}
    bucket: {{aliyun_cli_bucket}}
    regexp: .*-cli-linux-3\.0\.(\d+)-amd64\.tgz
    region_name: {{aliyun_cli_region}}
    endpoint: oss-((aliyun_cli_region)).aliyuncs.com
