name: Testing Coverage Rate Checks
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
    paths:
      - .github/workflows/testing-coverage-rate.yml
      - .go-version
      - alicloud/*.go

jobs:
  TestingCoverageRate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Checking testing coverage rate
        run: |
          git diff HEAD^ HEAD > diff.out
          go run scripts/testing/testing_coverage_rate_check.go -fileNames="diff.out"
